#!/command/with-contenv bash
response=$(curl --location --insecure --silent http://localhost/up)

if [[ $response == "OK" ]]; then
	exit 0
else
	echo "❌ There seems to be a failure in checking the web server + Octane. Here's the response:"
	echo $response
	exit 1
fi
