name: Docker Publish (Production Images)

on:
  push:
    branches:
      - main

jobs:
  octane-nginx:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      upstream-channel-prefix: ''
      tag-prefix: ''
      php-variation: octane-nginx
      checkout-type: latest-stable
    secrets: inherit
